#!/bin/bash
set -e

# color bash output
RED='\033[0;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

help_load() {
echo -e "Usage: jsh ${GREEN}load${NC} [USER]"
  exit 1
}

[ ! -n "$1" ] && help_load

# define default variables
USER=$1
WORKDIR=$2


# add rc file
JSHRC="${WORKDIR}/registry/${USER}.jshrc"
# allow configurable shell
bash -i <<< 'source ${WORKDIR}/registry/${USER}.jshrc; \
clear; echo ${GREEN}✔${NC} Successfully loaded ${GREEN}${USER}${NC}; \
exec </dev/tty;'
