#!/bin/bash
set -e

# color bash output
RED='\033[0;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

help_unload() {
echo -e "Usage: jsh ${GREEN}unload${NC}"
  exit 1
}

[ -n "$1" ] && help_unload

# revert to original terminal
$0
