#!/bin/bash
set -e

# color bash output
RED='\033[0;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

help_view() {
echo -e "Usage: jsh ${GREEN}view${NC}"
  exit 1
}

# define default variables
WORKDIR=$1

# list available files in registry
(printf ${GREEN}"PROFILES${NC}\n"; ls -1 "$WORKDIR"/registry | sed -e 's/\.jshrc$//') | column -t